### ISSUE TITLE
eth-docker.net search function

### ISSUE THREAD

**Issue by zer0cee** [eth-educators/website#31]
Hi,

the search in eth-docker.net is not working.

![grafik](https://github.com/eth-educators/website/assets/75437411/062155cd-ac1c-4937-956c-7aaa731f47b9)

Screenshot is attached. It's not working on any of my webbrowsers.

Kind regards

**Comment by hanniabu** [comment]
Thanks for reporting @zer0cee! This is a known issue that we haven't gotten around to looking into yet. Closing this issue since it was submitted under the wrong repo.
