### ISSUE TITLE
A UPS is unnecessary and adds to the complexity of a home staking setup

### ISSUE THREAD

**Issue by chrishobcroft** [eth-educators/website#99]
## Summary

So, I get the value of a uninterrupted power supply (UPS). They are vital when running mission-critical infra where downtime is absolutely unacceptable and to be avoided at all costs.

I would argue that in the case of a home validator setup, they are an unnecessary addition due to the added complexity of another 2 components (UPS, smartplug) in the setup.

I acknowledge that these are not listed as "required" but "recommended", but this still unnecessarily complicates what could otherwise be a very simple setup (see illustration below).

Also consider the environmental impact of including battery infrastructure (Lead Acid) and try to think about reducing Ethereum's contributions to sustainability.

Let's not forget that the Ethereum network is designed from the bottom-up to be resilient due to its distributed nature, and thus building moar complexity into individual nodes is in some ways counterintuitive.

From a cost/benefit perspective, it is also highly questionable whether the cost of the additional components is at all necessary below a certain number of validators, given the limited punitive nature of missed attestations.

## An illustration

Taking the setup without the UPS, there are 5 components required in addition to your existing home router (Motherboard, SSD, RAM, Power, Ethernet), all of which are readily available consumer products. It requires 4 connections (SSD to Motherboard, RAM to Motherboard, Motherboard to Power, Motherboard to Ethernet), all of which are well documented, and this requires no alteration to existing network infra (home router).

Adding the UPS increases the total number of components to 7, with the additional 2 items being specialist products (not to mention only compatible with Type A / Type B plugs [optimised for North America](https://www.worldstandards.eu/electricity/plugs-and-sockets/)). It increases the number of connections by 1 (UPS to Power) and also requires a change to a staker's existing network infrastructure (plug Router to UPS), which while being minimal, is non-zero.

This 40% increase in number of components increases the number of failure modes to consider, and the introduction of specialist region-specific hardware adds to the burden of international wannabe home-stakers.

## Proposed solution

I propose to communicate the UPS as being "optional" instead of "recommended", and for [the guide](https://ethstaker.cc/staking-hardware) to split out the UPS and smart plug into a separate section of the hardware setup guide, and explain that these are for advanced users, or for people staking many Validators, and for whom missed epochs are very costly.

## Alternative solution

To subtract the UPS altogether, and show the 4-component option in all its simplicity.

This can have the benefit of fully highlighting how simple it really can be to get started, without risking overwhelming novice hardware infrastructure operators with unnecessary complexity.

**Comment by nixorokish** [comment]
i like this. i've asked the illustrator to do a second 'minimal validator setup' illustration and maybe @hanniabu can add a toggle to show a minimal setup vs a comprehensive one?

**Comment by hanniabu** [comment]
@chrishobcroft the hardware page has been updated with the ability to toggle between a minimal and comprehensive setup

**Comment by chrishobcroft** [comment]
Nice
